### ISSUE TITLE
Nieprawidłowa wartość `productionEndpoint`

### ISSUE THREAD

**Issue by pszalko** [pay-now/omnipay-paynow#9]
Czy `productionEndpoint` jest na pewno dobrze podany?

```
abstract class AbstractPaynowRequest extends AbstractRequest
{
    /**
     * @var string
     */
    protected $sandboxEndpoint = 'https://api.sanddbox.paynow.pl/';

    /**
     * @var string
     */
    protected $productionEndpoint = 'https://api.sandbox.paynow.pl/';
```

**Comment by michalskladanowski** [comment]
Oczywiście adres był błędny, wrzuciliśmy poprawkę w [release 1.0.2](https://github.com/pay-now/omnipay-paynow/releases/tag/1.0.2). Dziękujemy za zauważenie błędu.

**Comment by pszalko** [comment]
Dzięki!

**Comment by pszalko** [comment]
W wersji 1.0.2 został jeszcze nieprawidłowy adres do `sandboxEndpoint` :)

**Comment by michalskladanowski** [comment]
poprawione 🤦  https://github.com/pay-now/omnipay-paynow/releases/tag/1.0.3
